# Some default settings to use for each job
defaults: &defaults
  docker:
      - image: circleci/node:8.9.4
  working_directory: ~/mobiledoc-react-renderer
  environment:
    TZ: "/usr/share/zoneinfo/America/New_York"

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: node-modules-cache-v2-{{ arch }}-{{ checksum "package-lock.json" }}
      - run:
          name: Setup NPM
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: node-modules-cache-v2-{{ arch }}-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: Build Application
          command: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
            - dist
  test:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          environment:
             NODE_ENV: test
          name: Test
          command: npm run test

workflows:
  version: 2
  build-test:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - test:
          requires:
            - build
